---
- name: Install Docker on Mac
  when: ansible_os_family == 'Darwin'
  block:
    - name: Install Docker using Homebrew
      become: true
      command: brew install docker docker-compose docker-machine
      tags: docker

- name: Install Docker on Linux (Debian/Ubuntu)
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
  block:
    - name: Install Docker dependencies
      # become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - jp
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - python3-docker

    - name: Add Docker official GPG key
      # become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      # become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker
      # become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: Create Docker Network
      # become: true
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        driver: bridge
    - name: Pull Geth Docker image
      docker_image:
        name: "{{ geth_docker_image }}"
        source: pull
    - name: Pull Lighthouse Docker image
      docker_image:
        name: "{{ lighthouse_docker_image }}"
        source: pull
    - name: Pull HA-Proxy Docker image
      docker_image:
        name: "{{ haproxy_docker_image }}"
        source: pull
  tags: docker
