---
- name: Install iptables
  become: true
  apt:
    name: iptables
    state: present

- name: Open tcp ports using iptables
  become: true
  shell: iptables -A INPUT -p tcp --dport {{ item }} -j ACCEPT
  loop:
    - 8080        #  json-rpc
    - 9090        #  rast api
    - 8888        #  HA Proxy stats
    - 30303
    - 30304
    - 9000

- name: Open udp ports p2p using iptables
  become: true
  shell: iptables -A INPUT -p udp --dport {{ item }} -j ACCEPT
  loop:
    - 30303
    - 30304
    - 9000



# - name: Install ufw package
#   become: true
#   ansible.builtin.package:
#     name: ufw
#     state: present

# - name: Enable firewall using ufw
#   become: true
#   ansible.builtin.command: ufw --force enable


# - name: Open ports 80 and 8080 for HA Proxy traffic
#   become: true
#   ufw:
#     rule: allow
#     port: "{{ item }}"
#     proto: tcp
#     state: enabled
#   loop:
#     - 80
#     - 8080

# - name: Allow TCP P2P traffic on ports 30303, 30304 and 9000
#   ufw:
#     rule: allow
#     proto: tcp
#     port: "{{ item }}"
#     state: enabled
#   loop:
#     - 30303
#     - 30304
#     - 9000

# - name: Allow UDP P2P traffic for ports 30303, 30304 and 9000
#   ufw:
#     rule: allow
#     proto: udp
#     port: "{{ item }}"
#     state: enabled
#   loop:
#     - 30303
#     - 30304
#     - 9000

# - name: Reload UFW
#   shell: ufw reload

# - name: Enable firewall using ufw
#   become: true
#   ansible.builtin.command: ufw --force enable
