---
- name: Install iptables
  become: true
  apt:
    name: iptables
    state: present

- name: Open tcp ports using iptables
  become: true
  shell: iptables -A INPUT -p tcp --dport {{ item }} -j ACCEPT
  loop:
    - 8080        #  HA Proxy stats
    - 30303
    - 30304
    - 9000

- name: Open udp ports p2p using iptables
  become: true
  shell: iptables -A INPUT -p udp --dport {{ item }} -j ACCEPT
  loop:
    - 30303
    - 30304
    - 9000
