---
- name: Copy HAProxy Configuration File
  ansible.builtin.template:
    src: "../templates/haproxy.cfg.j2"
    dest: "{{ app_data_path}}/{{ haproxy_node_name }}/config/haproxy.cfg"
  register: haproxy_config    
  become: true
  
- name: Start HAProxy Container
  docker_container:
    name: "{{ haproxy_node_name }}"
    image: "{{ haproxy_docker_image }}"
    ports:
      - "8080:8080"
    restart_policy: always
    state: started
    networks_cli_compatible: yes
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "{{ app_data_path }}/{{ haproxy_node_name }}/data:/usr/local/etc/haproxy"
      - "{{ app_data_path }}/{{ haproxy_node_name }}/config:/usr/local/etc/haproxy"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
