---
- name: Install HAProxy on ubuntu
  become: true
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy Configuration File
  become: true
  ansible.builtin.template:
    src: ../templates/haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"

- name: reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true

- name: Password for HAProxy stats UI
  debug:
    msg: "HAProxy stats UI username: scott, password: {{ random_password }}"
  tags: haproxy_ui
