- name: Ensure ethdata directory exists on localhost
  ansible.builtin.file:
    path: "{{ datadir }}"
    state: directory
    mode: '0755'
  become: true
  tags: datadir
- name: Copy ethnodes management scripts to the localhost
  ansible.builtin.copy:
    src: ../files/ethHA
    dest: /usr/sbin/ethHA
    owner: root
    group: root
    mode: u+rwx,g-wx,o-rwx
  tags: ethHA
  become: true
  # ansible.builtin.copy:
  #   src: "{{ item }}"
  #   dest: "/usr/sbin/{{ item }}"
  #   mode: '0755'
  # with_items:
  #   - "files/ethnodes"
  # become: true
  # tags: ethHA