- name: Ensure ethdata directory exists on localhost
  ansible.builtin.file:
    path: "{{ datadir }}"
    state: directory
    mode: '0755'
  tags: datadir
  register: datadir

- name: create data and config directory  for geth lighthous and HAProxy if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  loop:
    - "{{ app_data_path }}/{{ geth_node_name }}"
    - "{{ app_data_path }}/{{ geth_node_name }}/data"
    - "{{ app_data_path }}/{{ geth_node_name }}/config"
    - "{{ app_data_path }}/{{ lighthouse_node_name }}"
    - "{{ app_data_path }}/{{ lighthouse_node_name }}/data"
    - "{{ app_data_path }}/{{ lighthouse_node_name }}/config"
    - "{{ app_data_path }}/{{ haproxy_node_name }}"
    - "{{ app_data_path }}/{{ haproxy_node_name }}/data"
    - "{{ app_data_path }}/{{ haproxy_node_name }}/config"

- name: Copy ethnodes management scripts to the localhost
  ansible.builtin.copy:
    src: ../files/ethHA
    dest: /usr/sbin/ethHA
    owner: root
    group: root
  tags: ethHA
  become: true

- name: Update permissions on /usr/sbin/ethHA
  ansible.builtin.file:
    path: /usr/sbin/ethHA
    mode: "a+x"
    owner: root
    group: root
  become: true

- name: Copy Geth cli to local node
  ansible.builtin.copy:
    src: ../files/geth-cli
    dest: /usr/sbin/geth-cli
    owner: root
    group: root
  tags: geth-cli
  become: true

- name: Copy Lighthouse cli to local node
  ansible.builtin.copy:
    src: ../files/lighthouse-cli
    dest: /usr/sbin/lighthouse-cli
    owner: root
    group: root
  tags: lighthous-cli
  become: true
