---
- name: reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true

- name: restart geth
  docker_container:
    name: "{{ geth_node_name }}"
    state: restarted
  become: true

- name: restart geth
  docker_container:
    name: "{{ geth_node_name }}"
    state: restarted
  become: true
