---
# handlers for restart HAProxy
- name: Restart HAProxy
  docker_container:
    name: "{{ haproxy_node_name }}"
    state: restarted
  become: true

# handlers for restart geth
- name: Restart geth
  docker_container:
    name: "{{ geth_node_name }}"
    state: restarted
  become: true

